banner:
  enable: true
  title: ä¿¡ä»°æ˜¯ä¸ºäº†è™šå¹»ä¹‹äºº
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

favicon: /favicon.ico

social:
  - name: GitHub
    link: https://github.com/aldlss
    icon: ri:github-line
    color: '#181717'
  - name: E-Mail
    link: mailto:aya@suwako.cn
    icon: ri:mail-line
    color: '#8E71C1'

bg_image:
  enable: true
  url: https://fastly.jsdelivr.net/gh/Ayaloia/ImgHosting/pic93083972_p0.jpg
  dark: https://fastly.jsdelivr.net/gh/Ayaloia/ImgHosting/pic100439997_p0.jpg
  blur: 1px # è®¾ç½®èƒŒæ™¯æ¨¡ç³Šç¨‹åº¦
  opacity: 0.8

avatar:
  enable: true
  url: https://fastly.jsdelivr.net/gh/Ayaloia/ImgHosting/pic65452214.jpg
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: false
    emoji: ğŸ˜­
    message: ä¸æƒ³ä¸Šå­¦

menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line
  #   # - path: https://www.yunyoujun.cn
  #   #   icon: ri:cloud-line
  #   #   count: ä½ çŒœ
  custom:
    title: åœŸè‘—ç¥çš„é¡¶ç‚¹
    path: https://god.suwako.cn
    icon: ri:settings-line

pages:
  # - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
  #   url: /links/
  #   icon: ri:genderless-line
  #   color: dodgerblue

toc:
  list_number: true
  max_depth: 6
  min_depth: 1
  placeholder: ç›®å½•å·²è¿›å…¥å¹»æƒ³
  collapse: true

post_edit:
  enable: true
  url: https://github.com/Ayaloia/aldlss.github.io/tree/master/source/

codeblock:
  copy_btn: true

creative_commons:
  license: by-nc-sa
  post: false
  language: deed.zh
  clipboard: false

lazyload:
  enable: true

reward:
  enable: false
  # icon: ri:hand-coin-line
  # comment: I'm so cute. Please give me money.
  # url: https://github.com/YunYouJun/yunyoujun.github.io/issues/96
  # methods:
  #   - name: æ”¯ä»˜å®
  #     path: .jpg
  #     color: '#00A3EE'
  #     icon: ri:alipay-line
  #     # link: https://xxxx
  #   - name: QQ æ”¯ä»˜
  #     path: .png
  #     color: '#12B7F5'
  #     icon: ri:qq-line
  #   - name: å¾®ä¿¡æ”¯ä»˜
  #     path: .jpg
  #     color: '#2DC100'
  #     icon: ri:wechat-pay-line

footer:
  since: 2022
  support:
    enable: true
    title: fasnakegod
    link: https://www.pixiv.net/users/8605991
    # logo: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/logo/upyun-logo.png
    prefix: èƒŒæ™¯å›¾å‡ºå¤„
    # suffix: 


say:
  enable: true
  api: /data/sentences.json
  # https://developer.hitokoto.cn/sentence/
  hitokoto:
    enable: false
    api: https://v1.hitokoto.cn

mourn:
  enable: false
  days:
    - 4-4

wordcloud:
  enable: true

engine_search:
  enable: false

algolia_search:
  enable: true
  hits:
    per_page: 10 # the number of search results per page

google_analytics:
  enable: true
  id: G-JLJZK2MK9C
  # æ³¨æ„ï¼šæœ€è¿‘æ–°å»ºçš„è°·æ­Œåˆ†æè´¦å·IDå·²ç»ä¿®æ”¹ï¼Œæ ¼å¼å¦‚ï¼šG-XXXXXXXXXXï¼Œå¯ä»¥ç›´æ¥å¡«å…¥idä¸€é¡¹ï¼ŒåŠŸèƒ½æ­£å¸¸ã€‚
  # ç«™ç‚¹é…ç½®æ–‡ä»¶`_config.yml`ä¸­çš„ç«™ç‚¹éƒ¨ç½²çš„ url åº”ä¸ CNAME ä¸­çš„åŸŸåï¼ˆæˆ–xxxxx.github.ioï¼‰ä¸€è‡´

baidu_push: true

wordcount:
  enable: true
  count: true
  time: true

pjax:
  enable: true

waline:
  enable: true
  serverURL: https://comment.blog.suwako.cn
